config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here


    namespace :admin do
        post '/chaindrive/import', to: "chaindrive#import", as: :chaindrive_import
        get '/chaindrive/import/plan/', to: "chaindrive#form", as: :chaindrive_form

        get '/chaindrive/revert/:id', to: "chaindrive#revert", as: :chaindrive_revert
        get '/import_logs', to: "import_log#index", as: :import_logs
        get '/import_log/:id', to: "import_log#show", as: :import_log

    end


end

app/models/import_log.rb
    class ImportLog < Spree::Base
      has_many :stock_movements, as: :originator, :class_name =>'Spree::StockMovement';

      has_many :reverters, class_name: "ImportLog", foreign_key: "reverted_id"
      belongs_to :reverted, class_name: "ImportLog"

      def is_reverted?
       return reverters.any?
      end

      def last_reverter
        return reverters.last
      end

      def revert
        revert_log = ImportLog.create(number: DateTime.now.to_s(:number), filename: 'revert "'+self.filename+'"', reverted_id: self.id)

        self.stock_movements.each do |movement|
            movement.stock_item.stock_location.revert_warehouse_item(movement, revert_log)
        end
      end

    end

app/controllers/spree/admin/import_log_controller.rb
module Spree
  module Admin
    class ImportLogController < Spree::Admin::BaseController
      def index
         @import_logs = ImportLog.all().order("created_at desc")
      end
      def show
        @import_log = ImportLog.find(params[:id])
      end
    end
  end
end

app/views/spree/admin/import_log/index.html.erb
<% if @import_logs.any? %>
    <table class="table" id='listing_stock_locations' data-hook>
      <thead>
      <tr data-hook="stock_locations_header">
        <th><%= Spree.t(:date) %></th>
        <th><%= t(:file_name) %></th>
        <th><%= Spree.t(:number) %></th>
      </tr>
      </thead>
      <tbody>
      <% @import_logs.each do |import_log| %>
          <tr>
            <td><%= import_log.created_at %></td>
            <td><%= import_log.filename %></td>
            <td><%= link_to import_log.number, admin_import_log_path(import_log)  %> </td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
    <div class="alert alert-info no-objects-found">
      <%= Spree.t(:no_resource_found) %>
    </div>
<% end %>

app/views/spree/admin/import_log/show.html.erb
<% content_for :page_title do %>
    <div><%= Spree.t(:import_log_for_import_log, import_log_date: @import_log.created_at) %></div>
    <% if @import_log.is_reverted? %>
        <div>reverté par <%= link_to @import_log.last_reverter.number, admin_import_log_path(@import_log.last_reverter) %> </div>
    <% end %>
    <div>message d'importation : <%=@import_log.message%></div>
<% end %>

<% content_for :page_actions do %>
    <span id="revert">
      <%= button_link_to "Retourner a l'importation précédente", spree.admin_chaindrive_revert_path(@import_log.id), { :icon => 'SS', :id => 'chaindrive_revert', :class => 'btn-primary btn' } %>
    </span>
<% end %>


<% if (@stock_movements = @import_log.stock_movements.page(params[:page])).any? %>
    <table class="table" id='listing_stock_movements'>
      <colgroup>
        <col style="width: 35%">
        <col style="width: 20%">
        <col style="width: 45%">
      </colgroup>
      <thead>
      <tr data-hook="admin_stock_movements_index_headers">
        <th><%= Spree.t(:stock_item) %>
        <th><%= Spree.t(:quantity_before) %></th>
        <th><%= Spree.t(:movement) %></th>
        <th><%= Spree.t(:quantity_after) %></th>
      </tr>
      </thead>
      <tbody>
      <% @stock_movements.each do |stock_movement|%>
          <tr id="<%= spree_dom_id stock_movement %>" data-hook="admin_stock_movements_index_rows">
            <td>
              <%= display_variant(stock_movement) %>
            </td>
            <td><%= stock_movement.quantity_before %></td>
            <td><%= stock_movement.quantity %></td>
            <td><%= stock_movement.quantity_after %></td>

          </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
    <div class="alert alert-info no-objects-found">
      <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::StockMovement)) %>
    </div>
<% end %>

<%= paginate @stock_movements %>